from .adafactor import Adafactor as GaLoreAdafactor
from .adamw import AdamW as GaLoreAdamW
from .adamw_sampling import AdamW as GaLoreAdamW_sampling
from .adamw_sampling1 import AdamW as GaLoreAdamW_sampling1
from .adamw_dst import AdamW as GaLoreAdamWdst
from .adamw_origin import AdamW as GaLoreAdamW0
from .adamw_momentum import AdamW as GaLoreAdamWMomemtum
from .adamw_test import AdamW as GaLoreAdamW1
from .adamw8bit import AdamW8bit as GaLoreAdamW8bit
from .adamw_origin_inplace import AdamW as GaLoreAdamWInplace